import './globals.css'
import { Inter } from 'next/font/google';
import { Navbar, Footer, Layout } from '@/components';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My Ecommerce',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <body className={inter.className}>{children}</body> */}
      <body className={inter.className}>
        <header>
          <Navbar />
        </header>
        <main className='main-container'>
            {children}
        </main>
        <footer>
            <Footer />
        </footer>
        
        </body>
    </html>
  )
}
